language: python
python:
  - "3.6"
cache: pip

install:
  - make install
  - python -m nltk.downloader perluniprops nonbreaking_prefixes punkt

script:
  - make lint || travis_terminate 1
  - make test

branches:
  only:
  - master
  - /v\d+\.\d+\.\d+/  # Build tags
