language: python
python:
  - "3.6"
cache: pip

install:
  - pip install -r requirements/ci.txt
  - pip install .
  - python -m nltk.downloader perluniprops nonbreaking_prefixes punkt

script:
  - nosetests -v

branches:
  only:
  - master
  - /v\d+\.\d+\.\d+/  # Build tags
