matrix:
  include:
  # - os: linux
  #   python: 2.7
  #   env: PYTHON_VERSION=2.7
  - os: linux
    python: 3.5
    env: PYTHON_VERSION=3.5
  - os: linux
    python: 3.6
    env: PYTHON_VERSION=3.6
  # - os: osx
  #   language: generic
  #   env:
  #   - PYTHON_VERSION=2.7
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.5
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.6

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == 2.* ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == 3.* ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == 2.* ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == 3.* ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --add channels conda-forge
  - echo $PYTHON_VERSION
  - conda create -n testenv python=$PYTHON_VERSION  --yes
  - source activate testenv

install:
  - conda install --yes python=$PYTHON_VERSION pip scikit-learn nose
  - pip install --process-dependency-links git+https://github.com/anhaidgroup/deepmatcher | cat
  - pip install torch>=1.0.1
  - python -m nltk.downloader perluniprops nonbreaking_prefixes punkt

script:
  - nosetests -v
